import React, { useState, useEffect } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useLoan } from '@/context/LoanContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area'; // Assuming ScrollArea will be generated by shadcn

const AuditTrailViewer = ({ displayMessage }) => {
  const { isAuthenticated, user } = useAuth();
  const { applications } = useLoan();
  const [selectedApplicationId, setSelectedApplicationId] = useState('');
  const [applicationAudit, setApplicationAudit] = useState(null);

  // Guardrail: Access control for non-authenticated or incorrect role
  if (!isAuthenticated || (user?.role !== 'officer' && user?.role !== 'underwriter' && user?.role !== 'manager')) {
    displayMessage('destructive', 'Access Denied', 'You need loan management permissions to view the audit trail.');
    return (
      <Card className="w-full max-w-md mx-auto my-8">
        <CardHeader>
          <CardTitle className="text-destructive">Access Denied</CardTitle>
          <CardDescription>Application Audit Trail</CardDescription>
        </CardHeader>
        <CardContent>
          <p className="text-destructive">Only loan officers, underwriters, and managers can view the audit trail.</p>
        </CardContent>
      </Card>
    );
  }

  useEffect(() => {
    // If an application ID is pre-selected or entered, update the audit display
    if (selectedApplicationId) {
      const app = applications.find(a => a.id === selectedApplicationId);
      setApplicationAudit(app || null);
    } else {
      setApplicationAudit(null);
    }
  }, [selectedApplicationId, applications]);

  const handleSearch = (e) => {
    e.preventDefault();
    const appId = e.target.elements.appId.value.trim();
    if (appId) {
      setSelectedApplicationId(appId);
      const app = applications.find(a => a.id.toLowerCase() === appId.toLowerCase());
      if (!app) {
        displayMessage('info', 'No Application Found', `No application found with ID "${appId}".`);
      }
    } else {
      setSelectedApplicationId('');
      displayMessage('info', 'Search Cleared', 'Please enter an Application ID to view its audit trail.');
    }
  };

  const currentApp = applicationAudit;

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Application Audit Trail</CardTitle>
        <CardDescription>View all changes and approval/rejection events on an application.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <form onSubmit={handleSearch} className="flex items-end gap-4">
          <div className="flex-1 space-y-2">
            <Label htmlFor="appId">Enter Application ID</Label>
            <Input
              id="appId"
              type="text"
              placeholder="e.g., LA001, LA002"
              value={selectedApplicationId}
              onChange={(e) => setSelectedApplicationId(e.target.value)}
            />
          </div>
          <Button type="submit">View Audit Trail</Button>
        </form>

        {currentApp ? (
          <div>
            <h6 className="text-lg font-semibold mb-2">Audit Trail for Application {currentApp.id} ({currentApp.customerName})</h6>
            {currentApp.auditTrail && currentApp.auditTrail.length > 0 ? (
              <div className="rounded-md border overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Timestamp</TableHead>
                      <TableHead>User/System</TableHead>
                      <TableHead>Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {currentApp.auditTrail
                      .sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp))
                      .map((entry, index) => (
                        <TableRow key={index}>
                          <TableCell className="font-mono text-xs text-muted-foreground">{new Date(entry.timestamp).toLocaleString()}</TableCell>
                          <TableCell className="font-medium">{entry.user}</TableCell>
                          <TableCell>{entry.action}</TableCell>
                        </TableRow>
                      ))}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <p className="text-muted-foreground italic">No audit trail events recorded for this application yet.</p>
            )}
          </div>
        ) : (
          <p className="text-muted-foreground italic">Enter an Application ID to view its audit history.</p>
        )}
      </CardContent>
    </Card>
  );
};

export default AuditTrailViewer;